//! Hostile-input robustness for the binary HTTP API.
//!
//! The contract this file pins is the one `src/api.rs` opens with: *no byte
//! string a caller can send may reach a panicking code path*. Concretely,
//! for every payload exercised here the API must answer with a status that
//! blames the caller (`400`/`409`/`413`, plus `503` where a search can time
//! out) or succeed with a well-formed body — never `500`, never a dropped
//! connection, never a hang.
//!
//! Randomness is a deterministic xorshift64 seeded with fixed constants, so
//! a failure reproduces exactly on the next run and CI never goes flaky. No
//! fuzzing dependency is pulled in for that: the generator is ten lines.
//!
//! Every assertion names the offending payload in hex, because a fuzz
//! failure is worthless if you cannot replay the one body that caused it.

mod common;

use common::*;

use axum::body::Body;
use axum::http::{Method, Request, StatusCode};
use axum::Router;
use keres_engine::api::{
    self, ApiConfig, DEFAULT_MAX_HISTORY_MOVES, GAME_BYTES, MOVE_BYTES, PLAY_BYTES,
};
use keres_engine::game::Game;
use keres_engine::moves::{Move, PotentialMove};
use std::time::{Duration, Instant};

// ── Case counts ─────────────────────────────────────────────────────────────
//
// Tuned so the whole binary stays well under 30s in a debug build: the two
// search-free routes carry the bulk, the history route a third of that, and
// the engine route only a handful of cases (a search, even a rejected one,
// costs orders of magnitude more than a decode).

const MOVES_FUZZ_CASES: usize = 10_000;
const PLAY_FUZZ_CASES: usize = 10_000;
const MOVE_ENCODING_FUZZ_CASES: usize = 10_000;
const REPLAY_FUZZ_CASES: usize = 2_000;
const ENGINE_FUZZ_CASES: usize = 64;

/// Longest random body generated by the length-varying cases; comfortably
/// past every route's length check and past `/moves`' and `/play`' body
/// limits, so the `413` path gets exercised too.
const MAX_FUZZ_LEN: usize = 200;

// ── Deterministic PRNG ──────────────────────────────────────────────────────

/// xorshift64 — fixed seed in, identical byte stream out, every run.
struct Rng(u64);

impl Rng {
    fn new(seed: u64) -> Self {
        assert_ne!(seed, 0, "xorshift64 degenerates on a zero seed");
        Rng(seed)
    }

    fn next_u64(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.0 = x;
        x
    }

    fn next_u8(&mut self) -> u8 {
        // High bits of xorshift64 are the best-mixed ones.
        (self.next_u64() >> 56) as u8
    }

    /// Uniform-enough integer in `0..bound`.
    fn below(&mut self, bound: usize) -> usize {
        (self.next_u64() % bound as u64) as usize
    }

    fn bytes(&mut self, len: usize) -> Vec<u8> {
        (0..len).map(|_| self.next_u8()).collect()
    }
}

/// Hex of a whole payload — only ever formatted when an assertion fails, so
/// the full body is dumped rather than an unreplayable prefix.
fn hex(bytes: &[u8]) -> String {
    use std::fmt::Write;
    let mut out = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        let _ = write!(out, "{byte:02x}");
    }
    out
}

/// One fuzz body: a correct-length random payload, a random-length payload,
/// or a valid payload with a few bytes corrupted.
///
/// The mutation arm matters most: purely random bytes are rejected by the
/// very first square decode, whereas a lightly corrupted game usually still
/// decodes and drives move generation over boards no real game produces.
fn fuzz_body(rng: &mut Rng, case: usize, exact_len: usize, valid: &[u8]) -> Vec<u8> {
    match case % 4 {
        0 => rng.bytes(exact_len),
        1 | 2 => {
            let len = rng.below(MAX_FUZZ_LEN + 1);
            rng.bytes(len)
        }
        _ => {
            let mut body = valid.to_vec();
            for _ in 0..=rng.below(3) {
                let index = rng.below(body.len());
                body[index] = rng.next_u8();
            }
            body
        }
    }
}

// ── Assertions ──────────────────────────────────────────────────────────────

#[track_caller]
fn assert_status(route: &str, payload: &[u8], response: &Captured, allowed: &[StatusCode]) {
    assert!(
        allowed.contains(&response.status),
        "POST {route} answered {} — expected one of {:?}\n  payload ({} bytes): {}\n  response body: {:?}",
        response.status,
        allowed,
        payload.len(),
        hex(payload),
        response.text(),
    );
}

#[track_caller]
fn assert_octet_stream(route: &str, payload: &[u8], response: &Captured) {
    assert_eq!(
        response.content_type.as_deref(),
        Some("application/octet-stream"),
        "POST {route} answered 200 with content-type {:?}\n  payload: {}",
        response.content_type,
        hex(payload),
    );
}

/// A `/moves` success body: a whole number of decodable `PotentialMove`s.
#[track_caller]
fn assert_move_list_body(route: &str, payload: &[u8], response: &Captured) {
    assert_octet_stream(route, payload, response);
    assert_eq!(
        response.body.len() % MOVE_BYTES,
        0,
        "POST {route} answered 200 with a {}-byte move list (not a whole number of u16s)\n  payload: {}",
        response.body.len(),
        hex(payload),
    );
    for raw in response.u16s() {
        assert!(
            PotentialMove::try_from_u16(raw).is_some(),
            "POST {route} answered 200 with undecodable PotentialMove 0x{raw:04x}\n  payload: {}",
            hex(payload),
        );
    }
}

/// A success body that must be an 83-byte re-decodable game.
#[track_caller]
fn assert_game_body(route: &str, payload: &[u8], response: &Captured) {
    assert_octet_stream(route, payload, response);
    assert_eq!(
        response.body.len(),
        GAME_BYTES,
        "POST {route} answered 200 with {} bytes, not a {GAME_BYTES}-byte game\n  payload: {}",
        response.body.len(),
        hex(payload),
    );
    let mut bytes = [0u8; GAME_BYTES];
    bytes.copy_from_slice(&response.body);
    assert!(
        Game::from_binary(bytes).is_ok(),
        "POST {route} answered 200 with a game the decoder rejects: {}\n  payload: {}",
        hex(&response.body),
        hex(payload),
    );
}

/// A success body that must be a 2-byte decodable move.
#[track_caller]
fn assert_move_body(route: &str, payload: &[u8], response: &Captured) {
    assert_octet_stream(route, payload, response);
    assert_eq!(
        response.body.len(),
        MOVE_BYTES,
        "POST {route} answered 200 with {} bytes, not a {MOVE_BYTES}-byte move\n  payload: {}",
        response.body.len(),
        hex(payload),
    );
    let raw = u16::from_le_bytes([response.body[0], response.body[1]]);
    assert!(
        Move::try_from_u16(raw).is_some(),
        "POST {route} answered 200 with undecodable move 0x{raw:04x}\n  payload: {}",
        hex(payload),
    );
}

// ── Fixtures ────────────────────────────────────────────────────────────────

/// White king on e5, black king on f5, everything else empty, white to move —
/// a minimal board that passes `Board::validate`, so square 0 is the only
/// variable in the square-byte sweep.
fn two_king_payload(square_zero: u8) -> Vec<u8> {
    let mut payload = vec![0u8; GAME_BYTES];
    payload[0] = square_zero;
    payload[40] = 0b0111_1000; // White king (C=1, 111, 000).
    payload[41] = 0b0011_1000; // Black king (C=0, 111, 000).
    payload[BOARD_FLAGS] = 0b1000_0000; // White to move.
    payload
}

const BOARD_FLAGS: usize = GAME_BYTES - 2;
const BOARD_COUNTER: usize = GAME_BYTES - 1;

/// A router whose search cannot run away: the engine fuzz cases must not be
/// able to pin a blocking thread for a full minute if a random payload ever
/// does decode into a searchable position.
fn short_search_router() -> Router {
    api::router(ApiConfig {
        search_timeout: Duration::from_secs(5),
        search_queue_timeout: Duration::from_secs(1),
        ..ApiConfig::default()
    })
}

/// A fresh game plus a legal, non-`force_unstack` move for it: the canonical
/// 85-byte `/play` payload the truncation sweep chips away at.
async fn valid_play_payload() -> Vec<u8> {
    let game = new_game_bytes().await;
    let moves = post("/moves", game.clone()).await;
    assert_eq!(moves.status, StatusCode::OK);
    let potential = moves
        .u16s()
        .into_iter()
        .find(|raw| raw & 0x8000 == 0)
        .expect("the opening position has a move that does not force an unstack");
    let mut payload = game;
    payload.extend_from_slice(&move_bytes(potential_to_move(potential)));
    payload
}

/// A genuinely legal move history, built off-line with the library so the
/// history fuzzer has a corpus that survives past the first ply — random
/// bytes practically never do, and a replay that dies on move 0 exercises
/// none of the replay loop.
fn legal_history(rng: &mut Rng, plies: usize) -> Vec<u8> {
    let mut game = Game::new();
    let mut bytes = Vec::with_capacity(plies * MOVE_BYTES);
    for _ in 0..plies {
        let candidates: Vec<Move> = game
            .get_all_moves()
            .iter()
            .flat_map(|potential| potential.to_moves())
            .collect();
        if candidates.is_empty() {
            break;
        }
        let mv = candidates[rng.below(candidates.len())];
        if game.try_make(&mv).is_err() {
            break;
        }
        bytes.extend_from_slice(&mv.to_u16().to_le_bytes());
    }
    bytes
}

/// Status tally for a fuzz sweep.
///
/// "Never a 500" is trivially satisfied by a corpus that dies in the very
/// first length check, so each sweep also records what it actually provoked
/// and asserts that the interesting outcomes were reached — otherwise a
/// future change to the generator could silently turn these into no-ops.
#[derive(Debug, Default)]
struct Tally {
    total: usize,
    ok: usize,
    bad_request: usize,
    conflict: usize,
    too_large: usize,
}

impl Tally {
    fn record(&mut self, status: StatusCode) {
        self.total += 1;
        match status {
            StatusCode::OK => self.ok += 1,
            StatusCode::BAD_REQUEST => self.bad_request += 1,
            StatusCode::CONFLICT => self.conflict += 1,
            StatusCode::PAYLOAD_TOO_LARGE => self.too_large += 1,
            _ => {}
        }
    }

    #[track_caller]
    fn assert_reached(&self, route: &str, what: &str, count: usize, minimum: usize) {
        assert!(
            count >= minimum,
            "the {route} fuzz corpus only produced {count} {what} responses out of {} cases \
             (expected at least {minimum}) — the generator is no longer exercising that path",
            self.total,
        );
    }
}

// ── Fuzz sweeps ─────────────────────────────────────────────────────────────

#[tokio::test]
async fn fuzzed_moves_payloads_are_rejected_or_answered_with_a_valid_move_list() {
    let router = default_router();
    let valid = new_game_bytes().await;
    let mut rng = Rng::new(0x243F_6A88_85A3_08D3);
    let allowed = [
        StatusCode::OK,
        StatusCode::BAD_REQUEST,
        StatusCode::PAYLOAD_TOO_LARGE,
    ];

    let mut tally = Tally::default();
    for case in 0..MOVES_FUZZ_CASES {
        let body = fuzz_body(&mut rng, case, GAME_BYTES, &valid);
        let response = send(router.clone(), post_request("/moves", body.clone())).await;
        assert_status("/moves", &body, &response, &allowed);
        if response.status == StatusCode::OK {
            assert_move_list_body("/moves", &body, &response);
        }
        tally.record(response.status);
    }

    tally.assert_reached("/moves", "200", tally.ok, 200);
    tally.assert_reached("/moves", "400", tally.bad_request, 200);
    tally.assert_reached("/moves", "413", tally.too_large, 200);
}

#[tokio::test]
async fn fuzzed_play_payloads_are_rejected_or_answered_with_a_valid_game() {
    let router = default_router();
    let valid = valid_play_payload().await;
    let mut rng = Rng::new(0x1319_8A2E_0370_7344);
    let allowed = [
        StatusCode::OK,
        StatusCode::BAD_REQUEST,
        StatusCode::CONFLICT,
        StatusCode::PAYLOAD_TOO_LARGE,
    ];

    let mut tally = Tally::default();
    for case in 0..PLAY_FUZZ_CASES {
        let body = fuzz_body(&mut rng, case, PLAY_BYTES, &valid);
        let response = send(router.clone(), post_request("/play", body.clone())).await;
        assert_status("/play", &body, &response, &allowed);
        if response.status == StatusCode::OK {
            assert_game_body("/play", &body, &response);
        }
        tally.record(response.status);
    }

    tally.assert_reached("/play", "200", tally.ok, 20);
    tally.assert_reached("/play", "409", tally.conflict, 10);
    tally.assert_reached("/play", "400", tally.bad_request, 200);
    tally.assert_reached("/play", "413", tally.too_large, 200);
}

#[tokio::test]
async fn fuzzed_move_encodings_on_a_valid_game_are_rejected_or_played() {
    // The board half of a `/play` payload is fixed and valid here, so every
    // case lands on `Move::try_from_u16` and then on the legality check —
    // the two places a bad move used to be able to panic (moving from an
    // empty square, an off-board index).
    let router = default_router();
    let game = new_game_bytes().await;
    let mut rng = Rng::new(0x9216_D5D9_8979_FB1B);
    let allowed = [
        StatusCode::OK,
        StatusCode::BAD_REQUEST,
        StatusCode::CONFLICT,
    ];

    let mut tally = Tally::default();
    for _ in 0..MOVE_ENCODING_FUZZ_CASES {
        let raw = (rng.next_u64() >> 48) as u16;
        let mut body = game.clone();
        body.extend_from_slice(&move_bytes(raw));
        let response = send(router.clone(), post_request("/play", body.clone())).await;
        assert_status("/play", &body, &response, &allowed);
        if response.status == StatusCode::OK {
            assert_game_body("/play", &body, &response);
        }
        tally.record(response.status);
    }

    tally.assert_reached("/play", "400", tally.bad_request, 1000);
    tally.assert_reached("/play", "409", tally.conflict, 1000);
}

#[tokio::test]
async fn fuzzed_move_histories_are_rejected_or_answered_with_a_valid_game() {
    let router = default_router();
    let mut rng = Rng::new(0xA409_3822_299F_31D0);
    let allowed = [StatusCode::OK, StatusCode::BAD_REQUEST];

    let mut tally = Tally::default();
    for case in 0..REPLAY_FUZZ_CASES {
        let body = history_body(&mut rng, case);
        let response = send(router.clone(), post_request("/replay-moves", body.clone())).await;
        assert_status("/replay-moves", &body, &response, &allowed);
        if response.status == StatusCode::OK {
            assert_game_body("/replay-moves", &body, &response);
        }
        tally.record(response.status);
    }

    tally.assert_reached("/replay-moves", "200", tally.ok, 200);
    tally.assert_reached("/replay-moves", "400", tally.bad_request, 200);
}

/// One history-fuzz body: random bytes of a whole number of moves, random
/// bytes of an arbitrary length (so odd lengths hit the multiple-of-2
/// check), a legal history, or a legal history with one byte corrupted —
/// the last of which is the only cheap way to reach a rejection *deep* in
/// the replay loop rather than on move 0.
fn history_body(rng: &mut Rng, case: usize) -> Vec<u8> {
    match case % 4 {
        0 => {
            let len = rng.below(MAX_FUZZ_LEN + 1);
            rng.bytes(len - (len % MOVE_BYTES))
        }
        1 => {
            let len = rng.below(MAX_FUZZ_LEN + 1);
            rng.bytes(len)
        }
        2 => {
            let plies = rng.below(13);
            legal_history(rng, plies)
        }
        _ => {
            let plies = 1 + rng.below(12);
            let mut body = legal_history(rng, plies);
            if !body.is_empty() {
                let index = rng.below(body.len());
                body[index] = rng.next_u8();
            }
            body
        }
    }
}

#[tokio::test]
async fn fuzzed_engine_board_payloads_never_produce_a_server_error() {
    let router = short_search_router();
    let mut rng = Rng::new(0x082E_FA98_EC4E_6C89);
    let allowed = [
        StatusCode::OK,
        StatusCode::BAD_REQUEST,
        StatusCode::CONFLICT,
        StatusCode::SERVICE_UNAVAILABLE,
    ];

    // An empty board is structurally valid but has no legal move: it reaches
    // the search (unlike every random payload, which dies in the decoder)
    // and must come back as a 409, not a 500.
    let empty_board = vec![0u8; GAME_BYTES];
    let response = send(
        router.clone(),
        post_request("/engine-move-board", empty_board.clone()),
    )
    .await;
    assert_status(
        "/engine-move-board",
        &empty_board,
        &response,
        &[StatusCode::CONFLICT],
    );

    for _ in 0..ENGINE_FUZZ_CASES {
        let body = rng.bytes(GAME_BYTES);
        let response = send(
            router.clone(),
            post_request("/engine-move-board", body.clone()),
        )
        .await;
        assert_status("/engine-move-board", &body, &response, &allowed);
        if response.status == StatusCode::OK {
            assert_move_body("/engine-move-board", &body, &response);
        }
    }
}

// ── Exhaustive sweeps ───────────────────────────────────────────────────────

#[tokio::test]
async fn every_square_byte_value_is_decoded_or_rejected_without_a_server_error() {
    let router = default_router();
    let allowed = [StatusCode::OK, StatusCode::BAD_REQUEST];

    for value in 0u8..=255 {
        let body = two_king_payload(value);
        let response = send(router.clone(), post_request("/moves", body.clone())).await;
        assert_status("/moves", &body, &response, &allowed);
        if response.status == StatusCode::OK {
            assert_move_list_body("/moves", &body, &response);
        }
    }
}

#[tokio::test]
async fn every_flags_byte_value_is_accepted_or_rejected_without_a_server_error() {
    let router = default_router();
    let game = new_game_bytes().await;
    let allowed = [StatusCode::OK, StatusCode::BAD_REQUEST];

    for flags in 0u8..=255 {
        let mut body = game.clone();
        body[BOARD_FLAGS] = flags;
        let response = send(router.clone(), post_request("/moves", body.clone())).await;
        assert_status("/moves", &body, &response, &allowed);
        if response.status == StatusCode::OK {
            assert_move_list_body("/moves", &body, &response);
        }
    }
}

#[tokio::test]
async fn moves_without_capture_boundaries_never_produce_a_server_error() {
    let router = default_router();
    let game = new_game_bytes().await;
    let allowed = [StatusCode::OK, StatusCode::BAD_REQUEST];

    // 39/40 straddle the no-capture draw threshold, 254/255 the u8 ceiling.
    for counter in [0u8, 1, 39, 40, 254, 255] {
        let mut body = game.clone();
        body[BOARD_COUNTER] = counter;
        let response = send(router.clone(), post_request("/moves", body.clone())).await;
        assert_status("/moves", &body, &response, &allowed);
        if response.status == StatusCode::OK {
            assert_move_list_body("/moves", &body, &response);
        }
    }
}

#[tokio::test]
async fn every_move_bit_pattern_boundary_is_rejected_or_played_without_a_server_error() {
    let router = default_router();
    let game = new_game_bytes().await;
    let allowed = [
        StatusCode::OK,
        StatusCode::BAD_REQUEST,
        StatusCode::CONFLICT,
    ];

    // Both flag bits × every interesting square index: 0 and 80 are the ends
    // of the legal range, 81 is the first off-board index the 7-bit field can
    // hold and 127 is its maximum.
    for force_unstack in [0u16, 1] {
        for unstack in [0u16, 1] {
            for from in [0u16, 80, 81, 127] {
                for to in [0u16, 80, 81, 127] {
                    let raw = (force_unstack << 15) | (unstack << 14) | (to << 7) | from;
                    let mut body = game.clone();
                    body.extend_from_slice(&move_bytes(raw));
                    let response = send(router.clone(), post_request("/play", body.clone())).await;
                    assert_status("/play", &body, &response, &allowed);
                    if response.status == StatusCode::OK {
                        assert_game_body("/play", &body, &response);
                    }
                }
            }
        }
    }
}

#[tokio::test]
async fn every_truncated_play_payload_is_rejected_and_only_the_full_one_succeeds() {
    let router = default_router();
    let payload = valid_play_payload().await;

    for len in 0..=PLAY_BYTES {
        let body = payload[..len].to_vec();
        let response = send(router.clone(), post_request("/play", body.clone())).await;
        if len == PLAY_BYTES {
            assert_status("/play", &body, &response, &[StatusCode::OK]);
            assert_game_body("/play", &body, &response);
        } else {
            assert_status("/play", &body, &response, &[StatusCode::BAD_REQUEST]);
        }
    }
}

// ── Transport-level abuse ───────────────────────────────────────────────────

#[tokio::test]
async fn abusive_content_headers_are_answered_with_a_sane_status() {
    let router = default_router();
    let game = new_game_bytes().await;
    // The body extractor is byte-oriented, so a wrong or absent media type is
    // allowed to succeed; what it may never do is fail as a server error.
    let sane = [
        StatusCode::OK,
        StatusCode::BAD_REQUEST,
        StatusCode::LENGTH_REQUIRED,
        StatusCode::PAYLOAD_TOO_LARGE,
        StatusCode::UNSUPPORTED_MEDIA_TYPE,
    ];

    let cases: Vec<(&str, Request<Body>)> = vec![
        (
            "bogus content-type",
            Request::builder()
                .method(Method::POST)
                .uri("/moves")
                .header("content-type", "text/html; charset=utf-8")
                .body(Body::from(game.clone()))
                .expect("valid request"),
        ),
        (
            "no content-type",
            Request::builder()
                .method(Method::POST)
                .uri("/moves")
                .body(Body::from(game.clone()))
                .expect("valid request"),
        ),
        (
            "content-length larger than the body",
            Request::builder()
                .method(Method::POST)
                .uri("/moves")
                .header("content-type", "application/octet-stream")
                .header("content-length", "9999")
                .body(Body::from(game.clone()))
                .expect("valid request"),
        ),
        (
            "content-length smaller than the body",
            Request::builder()
                .method(Method::POST)
                .uri("/moves")
                .header("content-type", "application/octet-stream")
                .header("content-length", "2")
                .body(Body::from(game.clone()))
                .expect("valid request"),
        ),
        (
            "content-length that is not a number",
            Request::builder()
                .method(Method::POST)
                .uri("/moves")
                .header("content-type", "application/octet-stream")
                .header("content-length", "not-a-number")
                .body(Body::from(game.clone()))
                .expect("valid request"),
        ),
    ];

    for (label, request) in cases {
        let response = send(router.clone(), request).await;
        assert_status(label, &game, &response, &sane);
        if response.status == StatusCode::OK {
            assert_move_list_body(label, &game, &response);
        }
    }
}

#[tokio::test]
async fn a_maximal_length_garbage_history_is_rejected_promptly() {
    let router = default_router();
    let mut rng = Rng::new(0x3F84_D5B5_B547_0917);
    // Exactly the cap: the length check passes, so the replay itself has to
    // be what stops this, and it has to stop fast.
    let body = rng.bytes(DEFAULT_MAX_HISTORY_MOVES * MOVE_BYTES);

    let started = Instant::now();
    let response = send(router.clone(), post_request("/replay-moves", body.clone())).await;
    let elapsed = started.elapsed();

    assert_status(
        "/replay-moves",
        &body,
        &response,
        &[StatusCode::BAD_REQUEST],
    );
    assert!(
        elapsed < Duration::from_secs(5),
        "a {}-move garbage history took {elapsed:?} to reject\n  payload: {}",
        DEFAULT_MAX_HISTORY_MOVES,
        hex(&body),
    );
}
