sidus_template:
    routes:
        index:
            template: 'actions/index.html.twig'
        play:
            template: 'actions/play.html.twig'
        rules:
            template: 'actions/rules.html.twig'
