use arx_engine::{
    engine::{BatchSimulationEngine, MoveGenerationEngine},
    Board, Game, Position, BOARD_SIZE,
};
use base64::{engine::general_purpose, Engine as _};
use clap::{Args, Parser, Subcommand};
use std::collections::HashSet;

#[derive(Parser)]
#[command(author, version, about = "Debug utility for Arx engine GPU shaders", long_about = None)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Compare moves generated by GPU shader vs Rust implementation
    CompareMoves(CompareMovesArgs),
    /// Evaluate a board position using GPU shaders
    EvaluateBoard(EvaluateBoardArgs),
}

#[derive(Args)]
struct CompareMovesArgs {
    /// Base64 encoded board data
    #[arg(long)]
    board: String,
}

#[derive(Args)]
struct EvaluateBoardArgs {
    /// Base64 encoded board data
    #[arg(long)]
    board: String,
    /// Search depth (default: 1)
    #[arg(long, default_value = "1")]
    depth: u32,
}

fn main() {
    let cli = Cli::parse();

    match cli.command {
        Commands::CompareMoves(args) => {
            if let Err(e) = compare_moves(&args.board) {
                eprintln!("Error: {}", e);
                std::process::exit(1);
            }
        }
        Commands::EvaluateBoard(args) => {
            if let Err(e) = evaluate_board(&args.board, args.depth) {
                eprintln!("Error: {}", e);
                std::process::exit(1);
            }
        }
    }
}

fn decode_board(board_str: &str) -> Result<Board, String> {
    match general_purpose::STANDARD.decode(board_str) {
        Ok(bytes) => {
            if bytes.len() != BOARD_SIZE + 2 {
                return Err(format!(
                    "Invalid data length: expected {} bytes, got {}",
                    BOARD_SIZE + 2,
                    bytes.len()
                ));
            }

            let mut board_data = [0; BOARD_SIZE + 2];
            for (i, &byte) in bytes.iter().enumerate() {
                board_data[i] = byte;
            }

            Board::from_binary(board_data)
        }
        Err(e) => Err(format!("Failed to decode base64 string: {}", e)),
    }
}

fn compare_moves(board_str: &str) -> Result<(), String> {
    println!("=== Move Comparison: GPU Shader vs Rust Implementation ===\n");

    // Decode board
    let board = decode_board(board_str)?;
    println!("Board state:");
    println!("  White to move: {}", board.is_white_to_move());
    println!("  Game over: {}", board.is_game_over());
    if board.is_game_over() {
        println!("  Result: {}", if board.is_draw() {
            "Draw"
        } else if board.white_wins() {
            "White wins"
        } else {
            "Black wins"
        });
    }
    println!("  Moves without capture: {}", board.moves_without_capture());
    println!();

    // Get Rust-generated moves
    let game = Game::from_board(board.clone());
    let rust_moves = game.get_all_moves();
    println!("Rust implementation generated {} moves", rust_moves.len());

    // Get GPU-generated moves
    let move_gen = MoveGenerationEngine::new_sync()
        .map_err(|e| format!("Failed to create GPU move generation engine: {}", e))?;
    
    let board_binary = board.to_binary();
    let gpu_moves_u16 = move_gen.generate_moves(&board_binary)?;
    println!("GPU shader generated {} moves", gpu_moves_u16.len());
    println!();

    // Convert GPU moves to PotentialMove format for comparison
    let gpu_moves: Vec<_> = gpu_moves_u16
        .iter()
        .map(|&m| arx_engine::game::PotentialMove::from_u16(m))
        .collect();

    // Convert both to sets of (from, to, force_unstack) tuples for comparison
    let rust_set: HashSet<_> = rust_moves
        .iter()
        .map(|m| (m.from.to_u8(), m.to.to_u8(), m.force_unstack))
        .collect();

    let gpu_set: HashSet<_> = gpu_moves
        .iter()
        .map(|m| (m.from.to_u8(), m.to.to_u8(), m.force_unstack))
        .collect();

    // Find differences
    let in_rust_not_gpu: Vec<_> = rust_set.difference(&gpu_set).collect();
    let in_gpu_not_rust: Vec<_> = gpu_set.difference(&rust_set).collect();

    if in_rust_not_gpu.is_empty() && in_gpu_not_rust.is_empty() {
        println!("✓ SUCCESS: Both implementations generate the same moves!");
    } else {
        println!("✗ MISMATCH DETECTED:");
        
        if !in_rust_not_gpu.is_empty() {
            println!("\n  Moves in Rust but NOT in GPU ({}):", in_rust_not_gpu.len());
            for &&(from, to, force_unstack) in &in_rust_not_gpu {
                let from_pos = Position::from_u8(from);
                let to_pos = Position::from_u8(to);
                println!(
                    "    {} -> {} {}",
                    from_pos.to_string(),
                    to_pos.to_string(),
                    if force_unstack { "(forced unstack)" } else { "" }
                );
            }
        }

        if !in_gpu_not_rust.is_empty() {
            println!("\n  Moves in GPU but NOT in Rust ({}):", in_gpu_not_rust.len());
            for &&(from, to, force_unstack) in &in_gpu_not_rust {
                let from_pos = Position::from_u8(from);
                let to_pos = Position::from_u8(to);
                println!(
                    "    {} -> {} {}",
                    from_pos.to_string(),
                    to_pos.to_string(),
                    if force_unstack { "(forced unstack)" } else { "" }
                );
            }
        }
    }

    // Display detailed move list if requested
    if rust_moves.len() < 50 {
        println!("\n=== Detailed Move List ===");
        println!("\nRust moves:");
        for m in &rust_moves {
            println!(
                "  {} -> {} {}",
                m.from.to_string(),
                m.to.to_string(),
                if m.force_unstack { "(forced unstack)" } else if m.unstackable { "(unstackable)" } else { "" }
            );
        }

        println!("\nGPU moves:");
        for m in &gpu_moves {
            println!(
                "  {} -> {} {}",
                Position::from_u8(m.from.to_u8()).to_string(),
                Position::from_u8(m.to.to_u8()).to_string(),
                if m.force_unstack { "(forced unstack)" } else if m.unstackable { "(unstackable)" } else { "" }
            );
        }
    }

    Ok(())
}

fn evaluate_board(board_str: &str, depth: u32) -> Result<(), String> {
    println!("=== Board Evaluation: GPU Shader ===\n");
    println!("Search depth: {}\n", depth);

    // Decode board
    let board = decode_board(board_str)?;
    println!("Board state:");
    println!("  White to move: {}", board.is_white_to_move());
    println!("  Game over: {}", board.is_game_over());
    println!();

    // Get all legal moves
    let game = Game::from_board(board.clone());
    let moves = game.get_all_moves();
    
    if moves.is_empty() {
        println!("No legal moves available");
        return Ok(());
    }

    println!("Evaluating {} legal moves...\n", moves.len());

    // Create batch simulation engine
    let batch_sim = BatchSimulationEngine::new_sync()
        .map_err(|e| format!("Failed to create GPU batch simulation engine: {}", e))?;

    // Evaluate each move
    let mut move_scores: Vec<(usize, i32, bool)> = Vec::new();
    let board_binary = board.to_binary();

    for (idx, potential_move) in moves.iter().enumerate() {
        let move_u16 = potential_move.to_u16();
        
        // For depth 1, just apply the move and evaluate
        if depth == 1 {
            let boards = vec![board_binary];
            let move_list = vec![move_u16];
            
            match batch_sim.process_batch(&boards, &move_list) {
                Ok(results) => {
                    if let Some(result) = results.first() {
                        if result.valid {
                            move_scores.push((idx, result.score, true));
                        } else {
                            move_scores.push((idx, 0, false));
                        }
                    }
                }
                Err(e) => {
                    eprintln!("  Warning: GPU evaluation failed for move {}: {}", idx, e);
                    move_scores.push((idx, 0, false));
                }
            }
        } else {
            // For deeper search, we'd need to implement recursive evaluation
            // For now, just do depth 1
            eprintln!("Warning: Depth > 1 not yet fully implemented, using depth 1");
            let boards = vec![board_binary];
            let move_list = vec![move_u16];
            
            match batch_sim.process_batch(&boards, &move_list) {
                Ok(results) => {
                    if let Some(result) = results.first() {
                        if result.valid {
                            move_scores.push((idx, result.score, true));
                        } else {
                            move_scores.push((idx, 0, false));
                        }
                    }
                }
                Err(e) => {
                    eprintln!("  Warning: GPU evaluation failed for move {}: {}", idx, e);
                    move_scores.push((idx, 0, false));
                }
            }
        }
    }

    // Sort by score (highest first)
    move_scores.sort_by(|a, b| b.1.cmp(&a.1));

    // Display results
    println!("=== Evaluation Results (sorted by score) ===\n");
    for (idx, score, valid) in move_scores {
        let m = &moves[idx];
        let status = if valid { "✓" } else { "✗" };
        println!(
            "{} {} -> {}: score = {:6} {}",
            status,
            m.from.to_string(),
            m.to.to_string(),
            score,
            if m.force_unstack { "(forced unstack)" } else if m.unstackable { "(unstackable)" } else { "" }
        );
    }

    Ok(())
}
