use arx_engine::{
    engine::{BatchSimulationEngine, MoveGenerationEngine},
    Board, Game, Position, BOARD_SIZE,
};
use base64::{engine::general_purpose, Engine as _};
use clap::{Args, Parser, Subcommand};
use std::collections::HashSet;

#[derive(Parser)]
#[command(author, version, about = "Debug utility for Arx engine GPU shaders", long_about = None)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Compare moves generated by GPU shader vs Rust implementation
    CompareMoves(CompareMovesArgs),
    /// Evaluate a board position using GPU shaders
    EvaluateBoard(EvaluateBoardArgs),
}

#[derive(Args)]
struct CompareMovesArgs {
    /// Base64 encoded board data
    #[arg(long)]
    board: String,
}

#[derive(Args)]
struct EvaluateBoardArgs {
    /// Base64 encoded board data
    #[arg(long)]
    board: String,
    /// Search depth (default: 1)
    #[arg(long, default_value = "1")]
    depth: u32,
}

fn main() {
    let cli = Cli::parse();

    match cli.command {
        Commands::CompareMoves(args) => {
            if let Err(e) = compare_moves(&args.board) {
                eprintln!("Error: {}", e);
                std::process::exit(1);
            }
        }
        Commands::EvaluateBoard(args) => {
            if let Err(e) = evaluate_board(&args.board, args.depth) {
                eprintln!("Error: {}", e);
                std::process::exit(1);
            }
        }
    }
}

fn decode_board(board_str: &str) -> Result<Board, String> {
    match general_purpose::STANDARD.decode(board_str) {
        Ok(bytes) => {
            if bytes.len() != BOARD_SIZE + 2 {
                return Err(format!(
                    "Invalid data length: expected {} bytes, got {}",
                    BOARD_SIZE + 2,
                    bytes.len()
                ));
            }

            let mut board_data = [0; BOARD_SIZE + 2];
            for (i, &byte) in bytes.iter().enumerate() {
                board_data[i] = byte;
            }

            Board::from_binary(board_data)
        }
        Err(e) => Err(format!("Failed to decode base64 string: {}", e)),
    }
}

fn compare_moves(board_str: &str) -> Result<(), String> {
    println!("=== Move Comparison: GPU Shader vs Rust Implementation ===\n");

    // Decode board
    let board = decode_board(board_str)?;
    println!("Board state:");
    println!("  White to move: {}", board.is_white_to_move());
    println!("  Game over: {}", board.is_game_over());
    if board.is_game_over() {
        println!("  Result: {}", if board.is_draw() {
            "Draw"
        } else if board.white_wins() {
            "White wins"
        } else {
            "Black wins"
        });
    }
    println!("  Moves without capture: {}", board.moves_without_capture());
    println!();

    // Get Rust-generated moves
    let game = Game::from_board(board.clone());
    let rust_moves = game.get_all_moves();
    println!("Rust implementation generated {} moves", rust_moves.len());

    // Get GPU-generated moves
    let move_gen = MoveGenerationEngine::new_sync()
        .map_err(|e| format!("Failed to create GPU move generation engine: {}", e))?;
    
    let board_binary = board.to_binary();
    let gpu_moves_u16 = move_gen.generate_moves(&board_binary)?;
    println!("GPU shader generated {} moves", gpu_moves_u16.len());
    println!();

    // Convert GPU moves to PotentialMove format for comparison
    let gpu_moves: Vec<_> = gpu_moves_u16
        .iter()
        .map(|&m| arx_engine::game::PotentialMove::from_u16(m))
        .collect();

    // Convert both to sets of (from, to, force_unstack) tuples for comparison
    let rust_set: HashSet<_> = rust_moves
        .iter()
        .map(|m| (m.from.to_u8(), m.to.to_u8(), m.force_unstack))
        .collect();

    let gpu_set: HashSet<_> = gpu_moves
        .iter()
        .map(|m| (m.from.to_u8(), m.to.to_u8(), m.force_unstack))
        .collect();

    // Find differences
    let in_rust_not_gpu: Vec<_> = rust_set.difference(&gpu_set).collect();
    let in_gpu_not_rust: Vec<_> = gpu_set.difference(&rust_set).collect();

    if in_rust_not_gpu.is_empty() && in_gpu_not_rust.is_empty() {
        println!("✓ SUCCESS: Both implementations generate the same moves!");
    } else {
        println!("✗ MISMATCH DETECTED:");
        
        if !in_rust_not_gpu.is_empty() {
            println!("\n  Moves in Rust but NOT in GPU ({}):", in_rust_not_gpu.len());
            for &&(from, to, force_unstack) in &in_rust_not_gpu {
                let from_pos = Position::from_u8(from);
                let to_pos = Position::from_u8(to);
                println!(
                    "    {} -> {} {}",
                    from_pos.to_string(),
                    to_pos.to_string(),
                    if force_unstack { "(forced unstack)" } else { "" }
                );
            }
        }

        if !in_gpu_not_rust.is_empty() {
            println!("\n  Moves in GPU but NOT in Rust ({}):", in_gpu_not_rust.len());
            for &&(from, to, force_unstack) in &in_gpu_not_rust {
                let from_pos = Position::from_u8(from);
                let to_pos = Position::from_u8(to);
                println!(
                    "    {} -> {} {}",
                    from_pos.to_string(),
                    to_pos.to_string(),
                    if force_unstack { "(forced unstack)" } else { "" }
                );
            }
        }
    }

    // Display detailed move list if requested
    if rust_moves.len() < 50 {
        println!("\n=== Detailed Move List ===");
        println!("\nRust moves:");
        for m in &rust_moves {
            println!(
                "  {} -> {} {}",
                m.from.to_string(),
                m.to.to_string(),
                if m.force_unstack { "(forced unstack)" } else if m.unstackable { "(unstackable)" } else { "" }
            );
        }

        println!("\nGPU moves:");
        for m in &gpu_moves {
            println!(
                "  {} -> {} {}",
                Position::from_u8(m.from.to_u8()).to_string(),
                Position::from_u8(m.to.to_u8()).to_string(),
                if m.force_unstack { "(forced unstack)" } else if m.unstackable { "(unstackable)" } else { "" }
            );
        }
    }

    Ok(())
}

fn evaluate_board(board_str: &str, depth: u32) -> Result<(), String> {
    println!("=== Board Evaluation: GPU Shader ===\n");
    println!("Search depth: {}\n", depth);

    // Decode board
    let board = decode_board(board_str)?;
    println!("Board state:");
    println!("  White to move: {}", board.is_white_to_move());
    println!("  Game over: {}", board.is_game_over());
    println!();

    // Get all legal moves
    let game = Game::from_board(board.clone());
    let moves = game.get_all_moves();
    
    if moves.is_empty() {
        println!("No legal moves available");
        return Ok(());
    }

    println!("Evaluating {} legal moves...\n", moves.len());

    // Create batch simulation engine
    let batch_sim = BatchSimulationEngine::new_sync()
        .map_err(|e| format!("Failed to create GPU batch simulation engine: {}", e))?;

    // Evaluate each move
    let mut move_scores: Vec<(usize, i32, bool)> = Vec::new();
    let board_binary = board.to_binary();

    for (idx, potential_move) in moves.iter().enumerate() {
        let move_u16 = potential_move.to_u16();
        
        // For depth 1, just apply the move and evaluate
        if depth == 1 {
            let boards = vec![board_binary];
            let move_list = vec![move_u16];
            
            match batch_sim.process_batch(&boards, &move_list) {
                Ok(results) => {
                    if let Some(result) = results.first() {
                        if result.valid {
                            move_scores.push((idx, result.score, true));
                        } else {
                            move_scores.push((idx, 0, false));
                        }
                    }
                }
                Err(e) => {
                    eprintln!("  Warning: GPU evaluation failed for move {}: {}", idx, e);
                    move_scores.push((idx, 0, false));
                }
            }
        } else {
            // For deeper search, we'd need to implement recursive evaluation
            // For now, just do depth 1
            eprintln!("Warning: Depth > 1 not yet fully implemented, using depth 1");
            let boards = vec![board_binary];
            let move_list = vec![move_u16];
            
            match batch_sim.process_batch(&boards, &move_list) {
                Ok(results) => {
                    if let Some(result) = results.first() {
                        if result.valid {
                            move_scores.push((idx, result.score, true));
                        } else {
                            move_scores.push((idx, 0, false));
                        }
                    }
                }
                Err(e) => {
                    eprintln!("  Warning: GPU evaluation failed for move {}: {}", idx, e);
                    move_scores.push((idx, 0, false));
                }
            }
        }
    }

    // Sort by score
    // Paranoid approach: highest score is best for White, lowest for Black
    if board.is_white_to_move() {
        move_scores.sort_by(|a, b| b.1.cmp(&a.1)); // Sort descending for White
    } else {
        move_scores.sort_by(|a, b| a.1.cmp(&b.1)); // Sort ascending for Black
    }

    // Display results
    println!("=== Evaluation Results (sorted by score) ===");
    println!("(Scores are from White's perspective: positive=good for White, negative=good for Black)\n");
    for (idx, score, valid) in move_scores {
        let m = &moves[idx];
        let status = if valid { "✓" } else { "✗" };
        println!(
            "{} {} -> {}: score = {:6} {}",
            status,
            m.from.to_string(),
            m.to.to_string(),
            score,
            if m.force_unstack { "(forced unstack)" } else if m.unstackable { "(unstackable)" } else { "" }
        );
    }

    Ok(())
}

// Public functions for testing
#[cfg(test)]
pub fn decode_board_for_test(board_str: &str) -> Result<Board, String> {
    decode_board(board_str)
}

#[cfg(test)]
pub fn evaluate_board_for_test(board_str: &str) -> Result<Vec<(Position, Position, i32, bool)>, String> {
    let board = decode_board(board_str)?;
    let game = Game::from_board(board.clone());
    let moves = game.get_all_moves();
    
    let batch_sim = BatchSimulationEngine::new_sync()
        .map_err(|e| format!("Failed to create GPU batch simulation engine: {}", e))?;
    
    let board_binary = board.to_binary();
    let mut results = Vec::new();
    
    for potential_move in moves.iter() {
        let move_u16 = potential_move.to_u16();
        let boards = vec![board_binary];
        let move_list = vec![move_u16];
        
        match batch_sim.process_batch(&boards, &move_list) {
            Ok(batch_results) => {
                if let Some(result) = batch_results.first() {
                    results.push((
                        potential_move.from.clone(),
                        potential_move.to.clone(),
                        result.score,
                        result.valid,
                    ));
                }
            }
            Err(_) => {
                results.push((
                    potential_move.from.clone(),
                    potential_move.to.clone(),
                    0,
                    false,
                ));
            }
        }
    }
    
    Ok(results)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_capture_evaluation() {
        // Test board from issue: Black Dragon+Soldier in G7, White Soldier in H6
        // Black to move, capturing H6 should show positive score
        let board_str = "BwYEBTglAAAHAAADAAAAAgAAAQEBAQEBMQEBAAAAAAAAAEEAAAAAAAAAAAAAAAAAAAAAAAAAQUFBQUFBAEFBAABCAAAAQwAAR0ZERXhFREZHAAU=";
        
        let board = decode_board_for_test(board_str);
        if let Err(e) = &board {
            println!("Skipping test: Failed to decode board - {}", e);
            return;
        }
        let board = board.unwrap();
        
        // Verify the setup
        assert!(!board.is_white_to_move(), "Should be Black's turn");
        
        let g7 = Position::new(6, 2); // G7
        let h6 = Position::new(7, 3); // H6
        
        let piece_g7 = board.get_piece(&g7);
        assert!(piece_g7.is_some(), "Should have piece at G7");
        let piece_g7 = piece_g7.unwrap();
        assert_eq!(piece_g7.color, arx_engine::board::Color::Black);
        assert_eq!(piece_g7.bottom, arx_engine::board::PieceType::Soldier);
        assert_eq!(piece_g7.top, Some(arx_engine::board::PieceType::Dragon));
        
        let piece_h6 = board.get_piece(&h6);
        assert!(piece_h6.is_some(), "Should have piece at H6");
        let piece_h6 = piece_h6.unwrap();
        assert_eq!(piece_h6.color, arx_engine::board::Color::White);
        assert_eq!(piece_h6.bottom, arx_engine::board::PieceType::Soldier);
        assert!(piece_h6.top.is_none(), "H6 should be a single soldier");
        
        // Try to evaluate with GPU
        let results = evaluate_board_for_test(board_str);
        if let Err(e) = &results {
            println!("Skipping test: GPU not available - {}", e);
            return;
        }
        let results = results.unwrap();
        
        // Find the G7->H6 move
        let capture_move = results.iter().find(|(from, to, _, valid)| {
            *valid && from.x == 6 && from.y == 2 && to.x == 7 && to.y == 3
        });
        
        assert!(capture_move.is_some(), "Should find G7->H6 move");
        let (_, _, score, _) = capture_move.unwrap();
        
        // Paranoid approach: scores are always from White's perspective
        // Black capturing a White soldier means Black gains material
        // This should result in a MORE NEGATIVE score (worse for White)
        // So we expect the capture to have a lower (more negative) score than non-capturing moves
        assert!(*score < 0, "Black capturing White soldier should have negative score (good for Black), got {}", score);
        
        // Compare with a non-capture move to verify the capture is valued
        // Find a non-capture move for comparison
        let non_capture = results.iter().find(|(from, to, _, valid)| {
            *valid && from.x == 6 && from.y == 2 && (to.x != 7 || to.y != 3)
        });
        
        if let Some((_, _, non_capture_score, _)) = non_capture {
            // The capture should be more favorable for Black (more negative) than non-capture
            assert!(*score < *non_capture_score, 
                "Capture move (score={}) should be more negative than non-capture (score={}) for Black", 
                score, non_capture_score);
        }
    }
}
