use crate::board::{Board, Color, Piece, Position, BOARD_SIZE};
use crate::game_over::{check_game_over, check_promotion};
use crate::moves::{Move, MoveGenerator, PotentialMove};
use once_cell::sync::Lazy;
use ahash::RandomState;

/// Stores the information needed to undo a move.
#[derive(Clone, Debug)]
pub struct UndoInfo {
    pub from_piece: Option<Piece>,
    pub to_piece: Option<Piece>,
    pub was_white_to_move: bool,
    pub prev_moves_without_capture: u8,
    pub prev_game_over: bool,
    pub prev_white_wins: bool,
    pub prev_draw: bool,
}

impl UndoInfo {
    /// Fast check: returns true if the move captured a king (immediate game over).
    pub fn is_king_captured(&self) -> bool {
        self.to_piece
            .map(|p| p.is_king())
            .unwrap_or(false)
    }
}

#[derive(Clone, Debug)]
pub struct Game {
    pub board: Board,
    white_to_move: bool,
    game_over: bool,
    white_wins: bool,
    draw: bool,
    moves_without_capture: u8,
}

impl Game {
    pub fn new() -> Self {
        Game {
            board: Board::new(),
            white_to_move: true,
            game_over: false,
            white_wins: false,
            draw: false,
            moves_without_capture: 0,
        }
    }

    pub fn from_board(board: Board) -> Self {
        Game {
            board,
            white_to_move: true,
            game_over: false,
            white_wins: false,
            draw: false,
            moves_without_capture: 0,
        }
    }

    // ── Accessors ────────────────────────────────────────────────────────────

    pub fn is_white_to_move(&self) -> bool {
        self.white_to_move
    }

    pub fn set_white_to_move(&mut self, v: bool) {
        self.white_to_move = v;
    }

    pub fn color_to_move(&self) -> Color {
        if self.white_to_move { Color::White } else { Color::Black }
    }

    pub fn is_game_over(&self) -> bool {
        self.game_over
    }

    pub fn white_wins(&self) -> bool {
        self.white_wins
    }

    pub fn is_draw(&self) -> bool {
        self.draw
    }

    pub fn moves_without_capture(&self) -> u8 {
        self.moves_without_capture
    }

    pub fn set_moves_without_capture(&mut self, count: u8) {
        self.moves_without_capture = count;
    }

    pub fn set_game_over(&mut self, game_over: bool, white_wins: bool, draw: bool) {
        self.game_over = game_over;
        self.white_wins = white_wins;
        self.draw = draw;
    }

    // ── Move generation (delegated to MoveGenerator) ─────────────────────────

    pub fn get_all_moves(&self) -> Vec<PotentialMove> {
        MoveGenerator::new(&self.board, self.white_to_move).get_all_moves()
    }

    pub fn get_moves(&self, position: &Position) -> Vec<PotentialMove> {
        MoveGenerator::new(&self.board, self.white_to_move).get_moves(position)
    }

    pub fn is_capture(&self, mv: &Move) -> bool {
        MoveGenerator::new(&self.board, self.white_to_move).is_capture(mv)
    }

    // ── Make / Unmake ────────────────────────────────────────────────────────

    /// Apply a move in-place and return undo information.
    /// Assumes the move is valid (generated by the move generator).
    /// Performs full game-over checking after the move.
    pub fn make(&mut self, mv: &Move) -> UndoInfo {
        self.make_inner(mv, true)
    }

    /// Apply a move in-place without checking game-over conditions.
    /// Useful for minimax search where a fast `UndoInfo::is_king_captured()`
    /// check can be used instead.
    pub fn make_unchecked(&mut self, mv: &Move) -> UndoInfo {
        self.make_inner(mv, false)
    }

    fn make_inner(&mut self, mv: &Move, check_game_over_flag: bool) -> UndoInfo {
        let undo = UndoInfo {
            from_piece: self.board.get_piece(&mv.from).copied(),
            to_piece: self.board.get_piece(&mv.to).copied(),
            was_white_to_move: self.white_to_move,
            prev_moves_without_capture: self.moves_without_capture,
            prev_game_over: self.game_over,
            prev_white_wins: self.white_wins,
            prev_draw: self.draw,
        };

        let piece = self.board.get_piece(&mv.from).copied().unwrap();

        let source_piece: Piece;
        if mv.unstack {
            // Remove top piece from source; top becomes the moving piece
            source_piece = Piece {
                color: piece.color,
                bottom: piece.top.unwrap(),
                top: None,
            };
            self.board.set_piece(
                &mv.from,
                Some(Piece {
                    color: piece.color,
                    bottom: piece.bottom,
                    top: None,
                }),
            );
        } else {
            source_piece = piece;
            self.board.set_piece(&mv.from, None);
        }

        let dest = self.board.get_piece(&mv.to).copied();
        let mut final_piece = source_piece;
        let mut was_capture = false;

        match dest {
            None => {
                self.board.set_piece(&mv.to, Some(final_piece));
            }
            Some(dest_piece) => {
                if dest_piece.color != source_piece.color {
                    was_capture = true;
                    self.board.set_piece(&mv.to, Some(final_piece));
                } else {
                    // Stack: moving piece on top, existing piece on bottom
                    self.board.stack_piece(&mv.to, source_piece)
                        .expect("stack_piece failed during make: invalid stacking");
                    final_piece = *self.board.get_piece(&mv.to)
                        .expect("piece missing after stack_piece");
                }
            }
        }

        // Check for promotion
        if let Some(promoted) = check_promotion(&final_piece, &mv.to) {
            self.board.set_piece(&mv.to, Some(promoted));
        }

        // Update moves_without_capture counter
        if was_capture {
            self.moves_without_capture = 0;
        } else {
            self.moves_without_capture = self.moves_without_capture.saturating_add(1);
        }

        // Switch turn
        self.white_to_move = !self.white_to_move;

        // Check for game over conditions
        if check_game_over_flag {
            let result = check_game_over(&self.board, self.moves_without_capture);
            if result.game_over {
                self.game_over = result.game_over;
                self.white_wins = result.white_wins;
                self.draw = result.draw;
            }
        }

        undo
    }

    /// Undo a move by restoring the saved state.
    pub fn unmake(&mut self, mv: &Move, undo: UndoInfo) {
        self.board.set_piece(&mv.from, undo.from_piece);
        self.board.set_piece(&mv.to, undo.to_piece);
        self.white_to_move = undo.was_white_to_move;
        self.moves_without_capture = undo.prev_moves_without_capture;
        self.game_over = undo.prev_game_over;
        self.white_wins = undo.prev_white_wins;
        self.draw = undo.prev_draw;
    }

    /// Apply a null move (pass turn without moving a piece).
    /// Returns the previous `white_to_move` value for undo.
    pub fn make_null_move(&mut self) -> bool {
        let prev = self.white_to_move;
        self.white_to_move = !self.white_to_move;
        prev
    }

    /// Undo a null move by restoring the side to move.
    pub fn unmake_null_move(&mut self, prev_white_to_move: bool) {
        self.white_to_move = prev_white_to_move;
    }

    // ── Factory methods ──────────────────────────────────────────────────────

    /// Replay a sequence of binary-encoded moves (each move is 2 bytes, u16 little-endian).
    /// Returns the resulting Game state.
    pub fn from_moves(move_bytes: &[u8]) -> Result<Self, String> {
        if move_bytes.len() % 2 != 0 {
            return Err("Move data length must be a multiple of 2".to_string());
        }
        let mut game = Game::new();
        for i in (0..move_bytes.len()).step_by(2) {
            let move_u16 = u16::from_le_bytes([move_bytes[i], move_bytes[i + 1]]);
            let mv = Move::from_u16(move_u16);
            let _undo = game.make(&mv);
        }
        Ok(game)
    }

    // ── Binary serialisation ─────────────────────────────────────────────────

    /// Serialize the full game state: 81 bytes (board) + 1 byte (flags) + 1 byte (counter).
    pub fn to_binary(&self) -> [u8; BOARD_SIZE + 2] {
        let mut binary = [0u8; BOARD_SIZE + 2];

        let board_bytes = self.board.to_binary();
        binary[..BOARD_SIZE].copy_from_slice(&board_bytes);

        // Pack boolean flags into the flags byte
        let mut flags = 0u8;
        if self.white_to_move {
            flags |= 0b10000000;
        }
        if self.game_over {
            flags |= 0b01000000;
        }
        if self.white_wins {
            flags |= 0b00100000;
        }
        if self.draw {
            flags |= 0b00010000;
        }
        binary[BOARD_SIZE] = flags;
        binary[BOARD_SIZE + 1] = self.moves_without_capture;

        binary
    }

    /// Deserialize a full game state from 83 bytes.
    pub fn from_binary(binary: [u8; BOARD_SIZE + 2]) -> Result<Self, String> {
        let mut board_bytes = [0u8; BOARD_SIZE];
        board_bytes.copy_from_slice(&binary[..BOARD_SIZE]);
        let board = Board::from_binary(&board_bytes)?;

        let flags = binary[BOARD_SIZE];
        let white_to_move = (flags & 0b10000000) != 0;
        let game_over = (flags & 0b01000000) != 0;
        let white_wins = (flags & 0b00100000) != 0;
        let draw = (flags & 0b00010000) != 0;
        let moves_without_capture = binary[BOARD_SIZE + 1];

        Ok(Game {
            board,
            white_to_move,
            game_over,
            white_wins,
            draw,
            moves_without_capture,
        })
    }

    /// Efficient board hash using a static ahash::RandomState
    pub fn board_hash(&self) -> u64 {
        static HASHER: Lazy<RandomState> = Lazy::new(|| RandomState::with_seed(0xDEAD_BEEF));
        let mut binary = [0u8; BOARD_SIZE + 1];

        let board_bytes = self.board.to_binary();
        binary[..BOARD_SIZE].copy_from_slice(&board_bytes);
        binary[BOARD_SIZE] = if self.white_to_move { 1 } else { 0 };

        HASHER.hash_one(binary)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::board::PieceType;

    fn empty_game() -> Game {
        Game::from_board(Board::empty())
    }

    // ── Make / Unmake tests ──────────────────────────────────────────────────

    #[test]
    fn make_unmake_roundtrip_restores_state() {
        let mut game = Game::new();
        let original_board = game.board;
        let original_wtm = game.white_to_move;

        let mv = Move {
            from: Position::new(0, 6),
            to: Position::new(0, 5),
            unstack: false,
        };

        let undo = game.make(&mv);
        assert_ne!(game.board, original_board);
        game.unmake(&mv, undo);
        assert_eq!(game.board, original_board);
        assert_eq!(game.white_to_move, original_wtm);
    }

    #[test]
    fn make_capture_and_unmake() {
        let mut game = empty_game();
        let white_soldier = Piece::new(Color::White, PieceType::Soldier, None);
        let black_soldier = Piece::new(Color::Black, PieceType::Soldier, None);
        let white_king = Piece::new(Color::White, PieceType::King, None);
        let black_king = Piece::new(Color::Black, PieceType::King, None);
        game.board.set_piece(&Position::new(0, 8), Some(white_king));
        game.board.set_piece(&Position::new(0, 0), Some(black_king));
        game.board.set_piece(&Position::new(4, 4), Some(white_soldier));
        game.board.set_piece(&Position::new(4, 3), Some(black_soldier));
        let original_board = game.board;

        let mv = Move {
            from: Position::new(4, 4),
            to: Position::new(4, 3),
            unstack: false,
        };

        let undo = game.make(&mv);
        assert!(game.board.get_piece(&Position::new(4, 4)).is_none());
        assert_eq!(
            game.board.get_piece(&Position::new(4, 3)).unwrap().color,
            Color::White
        );
        assert_eq!(game.moves_without_capture(), 0);

        game.unmake(&mv, undo);
        assert_eq!(game.board, original_board);
    }

    #[test]
    fn make_stacking_and_unmake() {
        let mut game = empty_game();
        let white_soldier = Piece::new(Color::White, PieceType::Soldier, None);
        let white_guard = Piece::new(Color::White, PieceType::Guard, None);
        let white_king = Piece::new(Color::White, PieceType::King, None);
        let black_king = Piece::new(Color::Black, PieceType::King, None);
        game.board.set_piece(&Position::new(0, 8), Some(white_king));
        game.board.set_piece(&Position::new(0, 0), Some(black_king));
        game.board.set_piece(&Position::new(3, 4), Some(white_soldier));
        game.board.set_piece(&Position::new(3, 3), Some(white_guard));
        let original_board = game.board;

        let mv = Move {
            from: Position::new(3, 4),
            to: Position::new(3, 3),
            unstack: false,
        };

        let undo = game.make(&mv);
        assert!(game.board.get_piece(&Position::new(3, 4)).is_none());
        let stacked = game.board.get_piece(&Position::new(3, 3)).unwrap();
        assert_eq!(stacked.bottom, PieceType::Guard);
        assert_eq!(stacked.top, Some(PieceType::Soldier));

        game.unmake(&mv, undo);
        assert_eq!(game.board, original_board);
    }

    // ── Promotion tests ──────────────────────────────────────────────────────

    #[test]
    fn test_soldier_promotion_to_paladin_white() {
        let mut game = Game::new();
        let soldier_pos = Position::new(4, 1);
        game.board.set_piece(
            &soldier_pos,
            Some(Piece::new(Color::White, PieceType::Soldier, None)),
        );

        let mv = Move {
            from: soldier_pos,
            to: Position::new(3, 0),
            unstack: false,
        };
        let _undo = game.make(&mv);

        let piece = game.board.get_piece(&Position::new(3, 0)).unwrap();
        assert_eq!(piece.color, Color::White);
        assert_eq!(piece.bottom, PieceType::Paladin);
        assert_eq!(piece.top, None);
    }

    #[test]
    fn test_soldier_promotion_to_paladin_black() {
        let mut game = Game::new();
        let soldier_pos = Position::new(4, 7);
        game.board.set_piece(
            &soldier_pos,
            Some(Piece::new(Color::Black, PieceType::Soldier, None)),
        );
        game.set_white_to_move(false);

        let mv = Move {
            from: soldier_pos,
            to: Position::new(3, 8),
            unstack: false,
        };
        let _undo = game.make(&mv);

        let piece = game.board.get_piece(&Position::new(3, 8)).unwrap();
        assert_eq!(piece.color, Color::Black);
        assert_eq!(piece.bottom, PieceType::Paladin);
        assert_eq!(piece.top, None);
    }

    #[test]
    fn test_ballista_promotion_to_rook_white() {
        let mut game = Game::new();
        let ballista_pos = Position::new(4, 1);
        game.board.set_piece(
            &ballista_pos,
            Some(Piece::new(Color::White, PieceType::Ballista, None)),
        );

        let mv = Move {
            from: ballista_pos,
            to: Position::new(4, 0),
            unstack: false,
        };
        let _undo = game.make(&mv);

        let piece = game.board.get_piece(&Position::new(4, 0)).unwrap();
        assert_eq!(piece.color, Color::White);
        assert_eq!(piece.bottom, PieceType::Rook);
        assert_eq!(piece.top, None);
    }

    #[test]
    fn test_ballista_promotion_to_rook_black() {
        let mut game = Game::new();
        let ballista_pos = Position::new(4, 7);
        game.board.set_piece(
            &ballista_pos,
            Some(Piece::new(Color::Black, PieceType::Ballista, None)),
        );
        game.set_white_to_move(false);

        let mv = Move {
            from: ballista_pos,
            to: Position::new(4, 8),
            unstack: false,
        };
        let _undo = game.make(&mv);

        let piece = game.board.get_piece(&Position::new(4, 8)).unwrap();
        assert_eq!(piece.color, Color::Black);
        assert_eq!(piece.bottom, PieceType::Rook);
        assert_eq!(piece.top, None);
    }

    #[test]
    fn test_soldier_no_promotion_middle_board() {
        let mut game = Game::new();
        let soldier_pos = Position::new(4, 5);
        game.board.set_piece(
            &soldier_pos,
            Some(Piece::new(Color::White, PieceType::Soldier, None)),
        );

        let mv = Move {
            from: soldier_pos,
            to: Position::new(3, 4),
            unstack: false,
        };
        let _undo = game.make(&mv);

        let piece = game.board.get_piece(&Position::new(3, 4)).unwrap();
        assert_eq!(piece.color, Color::White);
        assert_eq!(piece.bottom, PieceType::Soldier);
        assert_eq!(piece.top, None);
    }

    #[test]
    fn test_stacked_soldier_promotion() {
        let mut game = Game::new();
        let stack_pos = Position::new(4, 1);
        game.board.set_piece(
            &stack_pos,
            Some(Piece::new(
                Color::White,
                PieceType::Guard,
                Some(PieceType::Soldier),
            )),
        );

        let mv = Move {
            from: stack_pos,
            to: Position::new(3, 0),
            unstack: true,
        };
        let _undo = game.make(&mv);

        let piece = game.board.get_piece(&Position::new(3, 0)).unwrap();
        assert_eq!(piece.color, Color::White);
        assert_eq!(piece.bottom, PieceType::Paladin);
        assert_eq!(piece.top, None);
    }

    #[test]
    fn test_other_pieces_no_promotion() {
        let mut game = Game::new();
        let guard_pos = Position::new(4, 1);
        game.board.set_piece(
            &guard_pos,
            Some(Piece::new(Color::White, PieceType::Guard, None)),
        );

        let mv = Move {
            from: guard_pos,
            to: Position::new(3, 0),
            unstack: false,
        };
        let _undo = game.make(&mv);

        let piece = game.board.get_piece(&Position::new(3, 0)).unwrap();
        assert_eq!(piece.color, Color::White);
        assert_eq!(piece.bottom, PieceType::Guard);
        assert_eq!(piece.top, None);
    }

    #[test]
    fn test_stacked_soldier_on_soldier_promotion_white() {
        let mut game = Game::new();
        let stack_pos = Position::new(4, 1);
        game.board.set_piece(
            &stack_pos,
            Some(Piece::new(
                Color::White,
                PieceType::Soldier,
                Some(PieceType::Soldier),
            )),
        );

        let mv = Move {
            from: stack_pos,
            to: Position::new(3, 0),
            unstack: false,
        };
        let _undo = game.make(&mv);

        let piece = game.board.get_piece(&Position::new(3, 0)).unwrap();
        assert_eq!(piece.color, Color::White);
        assert_eq!(piece.bottom, PieceType::Paladin);
        assert_eq!(piece.top, Some(PieceType::Paladin));
    }

    #[test]
    fn test_stacked_soldier_on_soldier_promotion_black() {
        let mut game = Game::new();
        let stack_pos = Position::new(4, 7);
        game.board.set_piece(
            &stack_pos,
            Some(Piece::new(
                Color::Black,
                PieceType::Soldier,
                Some(PieceType::Soldier),
            )),
        );
        game.set_white_to_move(false);

        let mv = Move {
            from: stack_pos,
            to: Position::new(3, 8),
            unstack: false,
        };
        let _undo = game.make(&mv);

        let piece = game.board.get_piece(&Position::new(3, 8)).unwrap();
        assert_eq!(piece.color, Color::Black);
        assert_eq!(piece.bottom, PieceType::Paladin);
        assert_eq!(piece.top, Some(PieceType::Paladin));
    }

    #[test]
    fn test_stacked_ballista_on_ballista_promotion_white() {
        let mut game = Game::new();
        let stack_pos = Position::new(4, 1);
        game.board.set_piece(
            &stack_pos,
            Some(Piece::new(
                Color::White,
                PieceType::Ballista,
                Some(PieceType::Ballista),
            )),
        );

        let mv = Move {
            from: stack_pos,
            to: Position::new(4, 0),
            unstack: false,
        };
        let _undo = game.make(&mv);

        let piece = game.board.get_piece(&Position::new(4, 0)).unwrap();
        assert_eq!(piece.color, Color::White);
        assert_eq!(piece.bottom, PieceType::Rook);
        assert_eq!(piece.top, Some(PieceType::Rook));
    }

    #[test]
    fn test_stacked_ballista_on_ballista_promotion_black() {
        let mut game = Game::new();
        let stack_pos = Position::new(4, 7);
        game.board.set_piece(
            &stack_pos,
            Some(Piece::new(
                Color::Black,
                PieceType::Ballista,
                Some(PieceType::Ballista),
            )),
        );
        game.set_white_to_move(false);

        let mv = Move {
            from: stack_pos,
            to: Position::new(4, 8),
            unstack: false,
        };
        let _undo = game.make(&mv);

        let piece = game.board.get_piece(&Position::new(4, 8)).unwrap();
        assert_eq!(piece.color, Color::Black);
        assert_eq!(piece.bottom, PieceType::Rook);
        assert_eq!(piece.top, Some(PieceType::Rook));
    }

    #[test]
    fn test_stacked_soldier_on_guard_promotion() {
        let mut game = Game::new();
        let stack_pos = Position::new(4, 1);
        game.board.set_piece(
            &stack_pos,
            Some(Piece::new(
                Color::White,
                PieceType::Guard,
                Some(PieceType::Soldier),
            )),
        );

        let mv = Move {
            from: stack_pos,
            to: Position::new(3, 0),
            unstack: false,
        };
        let _undo = game.make(&mv);

        let piece = game.board.get_piece(&Position::new(3, 0)).unwrap();
        assert_eq!(piece.color, Color::White);
        assert_eq!(piece.bottom, PieceType::Guard);
        assert_eq!(piece.top, Some(PieceType::Paladin));
    }

    #[test]
    fn test_stacked_guard_on_soldier_promotion() {
        let mut game = Game::new();
        let stack_pos = Position::new(4, 1);
        game.board.set_piece(
            &stack_pos,
            Some(Piece::new(
                Color::White,
                PieceType::Soldier,
                Some(PieceType::Guard),
            )),
        );

        let mv = Move {
            from: stack_pos,
            to: Position::new(3, 0),
            unstack: false,
        };
        let _undo = game.make(&mv);

        let piece = game.board.get_piece(&Position::new(3, 0)).unwrap();
        assert_eq!(piece.color, Color::White);
        assert_eq!(piece.bottom, PieceType::Paladin);
        assert_eq!(piece.top, Some(PieceType::Guard));
    }

    #[test]
    fn test_stacked_ballista_on_soldier_promotion() {
        let mut game = Game::new();
        let stack_pos = Position::new(4, 1);
        game.board.set_piece(
            &stack_pos,
            Some(Piece::new(
                Color::White,
                PieceType::Soldier,
                Some(PieceType::Ballista),
            )),
        );

        let mv = Move {
            from: stack_pos,
            to: Position::new(4, 0),
            unstack: false,
        };
        let _undo = game.make(&mv);

        let piece = game.board.get_piece(&Position::new(4, 0)).unwrap();
        assert_eq!(piece.color, Color::White);
        assert_eq!(piece.bottom, PieceType::Paladin);
        assert_eq!(piece.top, Some(PieceType::Rook));
    }

    // ── Game over tests ──────────────────────────────────────────────────────

    #[test]
    fn test_king_capture_white_wins() {
        let mut game = empty_game();

        game.board.set_piece(
            &Position::new(4, 4),
            Some(Piece::new(Color::White, PieceType::King, None)),
        );
        game.board.set_piece(
            &Position::new(3, 1),
            Some(Piece::new(Color::White, PieceType::Soldier, None)),
        );
        game.board.set_piece(
            &Position::new(4, 0),
            Some(Piece::new(Color::Black, PieceType::King, None)),
        );

        let mv = Move {
            from: Position::new(3, 1),
            to: Position::new(4, 0),
            unstack: false,
        };
        let _undo = game.make(&mv);

        assert!(game.is_game_over());
        assert!(game.white_wins());
        assert!(!game.is_draw());
    }

    #[test]
    fn test_king_capture_black_wins() {
        let mut game = empty_game();

        game.board.set_piece(
            &Position::new(4, 4),
            Some(Piece::new(Color::Black, PieceType::King, None)),
        );
        game.board.set_piece(
            &Position::new(3, 7),
            Some(Piece::new(Color::Black, PieceType::Soldier, None)),
        );
        game.board.set_piece(
            &Position::new(4, 8),
            Some(Piece::new(Color::White, PieceType::King, None)),
        );
        game.set_white_to_move(false);

        let mv = Move {
            from: Position::new(3, 7),
            to: Position::new(4, 8),
            unstack: false,
        };
        let _undo = game.make(&mv);

        assert!(game.is_game_over());
        assert!(!game.white_wins());
        assert!(!game.is_draw());
    }

    #[test]
    fn test_draw_only_kings_remaining() {
        let mut game = empty_game();

        game.board.set_piece(
            &Position::new(4, 4),
            Some(Piece::new(Color::White, PieceType::King, None)),
        );
        game.board.set_piece(
            &Position::new(4, 5),
            Some(Piece::new(Color::Black, PieceType::King, None)),
        );
        game.board.set_piece(
            &Position::new(3, 3),
            Some(Piece::new(Color::Black, PieceType::Soldier, None)),
        );
        game.board.set_piece(
            &Position::new(4, 2),
            Some(Piece::new(Color::White, PieceType::Soldier, None)),
        );

        // White soldier captures black soldier
        let mv = Move {
            from: Position::new(4, 2),
            to: Position::new(3, 3),
            unstack: false,
        };
        let _undo = game.make(&mv);
        assert!(!game.is_game_over());

        // Black king captures white soldier -> only kings left
        let mv2 = Move {
            from: Position::new(4, 5),
            to: Position::new(3, 3),
            unstack: false,
        };
        let _undo2 = game.make(&mv2);
        assert!(game.is_game_over());
        assert!(game.is_draw());
    }

    #[test]
    fn test_draw_single_knight() {
        let mut game = empty_game();

        game.board.set_piece(
            &Position::new(4, 0),
            Some(Piece::new(Color::White, PieceType::King, None)),
        );
        game.board.set_piece(
            &Position::new(3, 0),
            Some(Piece::new(Color::White, PieceType::Knight, None)),
        );
        game.board.set_piece(
            &Position::new(4, 8),
            Some(Piece::new(Color::Black, PieceType::King, None)),
        );
        game.board.set_piece(
            &Position::new(5, 8),
            Some(Piece::new(Color::Black, PieceType::Knight, None)),
        );
        game.board.set_piece(
            &Position::new(4, 4),
            Some(Piece::new(Color::White, PieceType::Soldier, None)),
        );
        game.set_white_to_move(false);

        // Black knight captures soldier
        let mv = Move {
            from: Position::new(5, 8),
            to: Position::new(4, 4),
            unstack: false,
        };
        let _undo = game.make(&mv);

        assert!(game.is_game_over());
        assert!(game.is_draw());
    }

    #[test]
    fn test_draw_40_move_rule() {
        let mut game = empty_game();

        game.board.set_piece(
            &Position::new(0, 0),
            Some(Piece::new(Color::White, PieceType::King, None)),
        );
        game.board.set_piece(
            &Position::new(8, 8),
            Some(Piece::new(Color::Black, PieceType::King, None)),
        );
        game.board.set_piece(
            &Position::new(4, 4),
            Some(Piece::new(Color::White, PieceType::Soldier, None)),
        );
        game.board.set_piece(
            &Position::new(5, 5),
            Some(Piece::new(Color::Black, PieceType::Soldier, None)),
        );
        game.set_moves_without_capture(39);

        let mv = Move {
            from: Position::new(4, 4),
            to: Position::new(5, 3),
            unstack: false,
        };
        let _undo = game.make(&mv);

        assert!(game.is_game_over());
        assert!(game.is_draw());
        assert_eq!(game.moves_without_capture(), 40);
    }

    #[test]
    fn test_capture_resets_move_counter() {
        let mut game = empty_game();

        game.board.set_piece(
            &Position::new(0, 0),
            Some(Piece::new(Color::White, PieceType::King, None)),
        );
        game.board.set_piece(
            &Position::new(8, 8),
            Some(Piece::new(Color::Black, PieceType::King, None)),
        );
        game.board.set_piece(
            &Position::new(4, 5),
            Some(Piece::new(Color::White, PieceType::Soldier, None)),
        );
        game.board.set_piece(
            &Position::new(5, 4),
            Some(Piece::new(Color::Black, PieceType::Soldier, None)),
        );
        game.set_moves_without_capture(15);

        let mv = Move {
            from: Position::new(4, 5),
            to: Position::new(5, 4),
            unstack: false,
        };
        let _undo = game.make(&mv);

        assert_eq!(game.moves_without_capture(), 0);
    }

    #[test]
    fn test_cannot_move_when_game_over() {
        let mut game = Game::new();
        game.set_game_over(true, true, false);

        // Game is over, but make() assumes valid moves; we test the state is set
        assert!(game.is_game_over());
    }

    #[test]
    fn test_binary_encoding_with_game_state() {
        let mut game = Game::new();
        game.set_game_over(true, false, true);
        game.set_moves_without_capture(25);

        let binary = game.to_binary();
        let decoded_game = Game::from_binary(binary).unwrap();

        assert_eq!(decoded_game.is_game_over(), true);
        assert_eq!(decoded_game.white_wins(), false);
        assert_eq!(decoded_game.is_draw(), true);
        assert_eq!(decoded_game.moves_without_capture(), 25);
    }

    #[test]
    fn test_color_lock_draw() {
        let mut game = empty_game();

        game.board.set_piece(
            &Position::new(4, 4),
            Some(Piece::new(Color::White, PieceType::King, None)),
        );
        game.board.set_piece(
            &Position::new(4, 5),
            Some(Piece::new(Color::Black, PieceType::King, None)),
        );

        // White bishops on white squares
        game.board.set_piece(
            &Position::new(0, 0),
            Some(Piece::new(Color::White, PieceType::Bishop, None)),
        );
        game.board.set_piece(
            &Position::new(2, 0),
            Some(Piece::new(Color::White, PieceType::Bishop, None)),
        );

        // Black guards on black squares
        game.board.set_piece(
            &Position::new(0, 1),
            Some(Piece::new(Color::Black, PieceType::Guard, None)),
        );
        game.board.set_piece(
            &Position::new(2, 1),
            Some(Piece::new(Color::Black, PieceType::Guard, None)),
        );

        // White soldier on a black square to be captured
        game.board.set_piece(
            &Position::new(1, 2),
            Some(Piece::new(Color::White, PieceType::Soldier, None)),
        );
        game.set_white_to_move(false);

        let mv = Move {
            from: Position::new(0, 1),
            to: Position::new(1, 2),
            unstack: false,
        };
        let _undo = game.make(&mv);

        assert!(game.is_game_over());
        assert!(game.is_draw());
    }

    // ── UndoInfo::is_king_captured ──────────────────────────────────────────

    #[test]
    fn test_undo_info_king_captured() {
        let mut game = empty_game();
        game.board.set_piece(
            &Position::new(4, 4),
            Some(Piece::new(Color::White, PieceType::King, None)),
        );
        game.board.set_piece(
            &Position::new(3, 1),
            Some(Piece::new(Color::White, PieceType::Soldier, None)),
        );
        game.board.set_piece(
            &Position::new(4, 0),
            Some(Piece::new(Color::Black, PieceType::King, None)),
        );

        let mv = Move {
            from: Position::new(3, 1),
            to: Position::new(4, 0),
            unstack: false,
        };
        let undo = game.make(&mv);
        assert!(undo.is_king_captured());
    }

    #[test]
    fn test_undo_info_no_king_captured() {
        let mut game = empty_game();
        game.board.set_piece(
            &Position::new(4, 4),
            Some(Piece::new(Color::White, PieceType::King, None)),
        );
        game.board.set_piece(
            &Position::new(3, 1),
            Some(Piece::new(Color::White, PieceType::Soldier, None)),
        );
        game.board.set_piece(
            &Position::new(4, 0),
            Some(Piece::new(Color::Black, PieceType::King, None)),
        );
        game.board.set_piece(
            &Position::new(4, 2),
            Some(Piece::new(Color::Black, PieceType::Soldier, None)),
        );

        let mv = Move {
            from: Position::new(3, 1),
            to: Position::new(4, 2),
            unstack: false,
        };
        let undo = game.make(&mv);
        assert!(!undo.is_king_captured());
    }

    // ── make_unchecked ──────────────────────────────────────────────────────

    #[test]
    fn test_make_unchecked_skips_game_over() {
        let mut game = empty_game();
        game.board.set_piece(
            &Position::new(4, 4),
            Some(Piece::new(Color::White, PieceType::King, None)),
        );
        game.board.set_piece(
            &Position::new(3, 1),
            Some(Piece::new(Color::White, PieceType::Soldier, None)),
        );
        game.board.set_piece(
            &Position::new(4, 0),
            Some(Piece::new(Color::Black, PieceType::King, None)),
        );

        let mv = Move {
            from: Position::new(3, 1),
            to: Position::new(4, 0),
            unstack: false,
        };
        let undo = game.make_unchecked(&mv);
        // King was captured, but game_over flag is NOT set (unchecked)
        assert!(!game.is_game_over());
        // However, UndoInfo knows a king was captured
        assert!(undo.is_king_captured());

        game.unmake(&mv, undo);
        assert!(!game.is_game_over());
    }

    #[test]
    fn find_missed_king_captures() {
        use base64::{engine::general_purpose, Engine as _};

        let b64 = "Tx6XEEkcAQrBHIsEPhqABDYXiQa4UpRSuRIWD7sYkw6lXI8PPBkeFDIUhgKlDp8eqEoEBkUivQrEAg1UhQMNFJ0KjAoHBKgVyx0rUbkSlQU0FaIQuxWhFQgNKyNOHsYnmgiLCdAjTyi8ItAnEQcTDqUXggFHBIMKDgWcDq8SHQ8uEx4TpQrPZkwhTydFJ00nOhgmD5UUziJCHUUVOiIqDEgJGBESAKIngA0eCwgClgpKHA==";
        let move_bytes = general_purpose::STANDARD.decode(b64).unwrap();

        let mut game = Game::new();

        for i in (0..move_bytes.len()).step_by(2) {
            let move_u16 = u16::from_le_bytes([move_bytes[i], move_bytes[i + 1]]);
            let mv = Move::from_u16(move_u16);
            let move_num = i / 2 + 1;
            let side = if game.is_white_to_move() { "W" } else { "B" };

            // Before making the move, check if the side to move can capture the opponent's king
            let all_moves = game.get_all_moves();
            let mut king_capture_moves = Vec::new();
            for pm in &all_moves {
                for m in pm.to_moves() {
                    if let Some(piece) = game.board.get_piece(&m.to) {
                        if piece.is_king() && piece.color != game.color_to_move() {
                            let from_piece = game.board.get_piece(&m.from)
                                .map(|p| format!("{:?}/{:?}", p.bottom, p.top))
                                .unwrap_or("?".to_string());
                            king_capture_moves.push(format!("{} from {} to {} (piece: {})",
                                m.to_string(), m.from.to_string(), m.to.to_string(), from_piece));
                        }
                    }
                }
            }

            if !king_capture_moves.is_empty() {
                println!("=== Move {} ({}): KING CAPTURE AVAILABLE ===", move_num, side);
                for km in &king_capture_moves {
                    println!("  {}", km);
                }
                println!("  -> But played {}", mv.to_string());
                println!();
            }

            let _undo = game.make(&mv);
        }
    }
}
